language: node_js

node_js:
    - "7.5.0"

env:
    global:
        - CHROME_BIN="chromium-browser"
        - CXX=g++-4.8
        - DISPLAY=:99.0
        - NODE_ENV=test

dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

cache:
    yarn: true
    directories:
        - $(npm config get prefix)/bin/grunt-cli
        - node_modules

before_install:
    - sh -e /etc/init.d/xvfb start
    # Repo for Yarn
    - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq yarn

install:
    - "make --silent install"
